# Copyright (c) 2026 tro Contributors
# SPDX-License-Identifier: MIT
"""Backend application package for tro."""

from .auth import (
    get_current_user,
    require_landlord,
    require_tenant,
    router as auth_router,
)
from .compat import (
    APIRouter,
    Depends,
    FastAPI,
    Field,
    HTTPException,
    Session,
    SQLModel,
    col,
    create_engine,
    select,
    status,
)
from .database import engine, get_session, init_db
from .models import (
    DEFAULT_TIERS_JSON,
    Invoice,
    MeterReading,
    Property,
    Room,
    SystemConfig,
    User,
    generate_invite_code,
    get_default_tiers,
)
from .schemas import (
    PropertyCreate,
    PropertyOut,
    RoomCreate,
    RoomOut,
    SystemConfigUpdate,
    TokenResponse,
    UserLogin,
    UserOut,
    UserRegister,
)
from .security import (
    create_access_token,
    decode_access_token,
    get_password_hash,
    verify_password,
)

__all__ = [
    "SQLModel",
    "Field",
    "Session",
    "create_engine",
    "select",
    "col",
    "APIRouter",
    "Depends",
    "FastAPI",
    "HTTPException",
    "status",
    "engine",
    "get_session",
    "init_db",
    "User",
    "Property",
    "Room",
    "SystemConfig",
    "MeterReading",
    "Invoice",
    "generate_invite_code",
    "get_default_tiers",
    "DEFAULT_TIERS_JSON",
    "get_password_hash",
    "verify_password",
    "create_access_token",
    "decode_access_token",
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "UserOut",
    "PropertyCreate",
    "PropertyOut",
    "RoomCreate",
    "RoomOut",
    "SystemConfigUpdate",
    "auth_router",
    "get_current_user",
    "require_landlord",
    "require_tenant",
]
